[package]
name = "mochondrius/wally-test"
version = "0.1.0"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

[dependencies]
TestEZ = "roblox/testez@0.4.1"
Knit = "sleitnick/knit@^1.7.0"
Component = "sleitnick/component@2.3.0"
Promise = "evaera/promise@3.2.1"
Janitor = "howmanysmall/janitor@1.13.15"
Signal = "sleitnick/signal@1.1.0"
Remote = "sleitnick/remote@1.0.4"
Ser = "sleitnick/ser@1.0.4"
Hitbox = "nightcycle/hitbox@4.1.0"
TableUtil = "sleitnick/table-util@1.1.2"
GameAnalytics = "gameanalytics/gameanalytics-sdk@2.2.2"
Vinum = "sinlerdev/vinum@0.2.0"
Vusion = "sinlerdev/vusion@0.2.0"
Fusion = "ruizukun-dev/fusion@1.0.0"
ProfileService = "surnautica/profileservice@1.0.0"
Iris = "michael-48/iris@2.1.4"
PacketProfiler = "pysephwasntavailable/packetprofiler@1.4.5"